title: FINT
description: Forklaring og dokumentasjon for produktet FINT, og andre tjenesert levert av teknologiseksjonen hos Vigo IKS.
theme: just-the-docs

url: https://just-the-docs.github.io
toc: true
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
