title: FINT
description: Forklaring og dokumentasjon for produktet FINT, og andre tjenesert levert av teknologiseksjonen hos Vigo IKS.
theme: just-the-docs

url: https://just-the-docs.github.io
toc: true
aux_links:
  GitHub: https://github.com/FINTLabs
  Vigo IKS: https://www.vigoiks.no

heading_anchors: true

#logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: dark